---
abstract: 'swat tests for metacpan.org'
author:
  - 'Alexey Melezhik.'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
  File::ShareDir: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: swat-metacpan-web
no_index:
  directory:
    - inc
    - share
    - t
requires:
  DateTime: 0
  Time::Piece: '1.30'
  swat: 0.1.52
resources:
  license: http://dev.perl.org/licenses/
version: 0.1.3
